name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build web assets
      run: npm run build
      
    - name: Copy to Android
      run: npx cap copy android
      
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Build APK with toolchain override
      run: |
        cd android
        # Override Java version detection
        ./gradlew assembleDebug \
          -Dorg.gradle.java.home=$JAVA_HOME \
          -Porg.gradle.java.installations.auto-detect=false \
          --no-daemon \
          --stacktrace
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: sjekkid-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30

    - name: Upload APK to release (if tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: android/app/build/outputs/apk/debug/app-debug.apk
        name: SJEKK ID Android App ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}